### ISSUE TITLE
Full Page Caching workaround

### ISSUE THREAD

**Issue by fabian** [Remo/concrete5-performance-monitoring#4]
After installing the add-on I still noticed many requests reported as `index.php` in New Relic. It turns out the package is not loaded for pages served from the full page cache.

Unfortunately there's no way around this at the moment, see this related discussion in the Forums: [Full page cache and events](http://www.concrete5.org/community/forums/customizing_c5/full-page-cache-and-events).

My workaround is to add the following lines to the file `config/site_post_autoload.php`:

``` php
if (extension_loaded('newrelic')) {
    $r = Request::get();
    $url = '/' . $r->getRequestPath();
    newrelic_name_transaction($url);
}
```

**Comment by Remo** [comment]
In which case the whole add-on is pretty much useless ;-) I'll try to keep this in mind, maybe we can add a pre-full-page-cache-event someday, probably has to be 5.7
